name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          name: [linux, windows, macos]

          include:
            - name: linux
              os: ubuntu-latest
            - name: windows
              os: windows-latest
            - name: macos
              os: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal -c rustfmt,clippy

      - name: Clippy
        run: cargo clippy --manifest-path=rust/Cargo.toml

      - name: Build
        run: cargo build --manifest-path=rust/Cargo.toml --verbose

      - name: Run tests
        run: cargo test --manifest-path=rust/Cargo.toml --verbose
